In [1]:
import pandas as pd
df = pd.read_parquet("/kaggle/input/datasets/kylenaluan/user-segments")
sf_df = pd.read_parquet("/kaggle/input/datasets/kylenaluan/session-features")

In [2]:
df.head()

          cluster_id     cluster_label
user_id
10300217           0  Passive Browsers
29515875           2   Active Browsers
31198833           2   Active Browsers
33869381           0  Passive Browsers
34916060           0  Passive Browsers

In [3]:
sf_df.head()

,user_session,user_id,n_events,unique_products,session_start,session_end,n_carts,n_purchases,n_views,session_revenue,duration_seconds,converted,cart_abandoned,hour_of_day,day_of_week,month
0,00000042-3e3f-42f9-810d-f3d264139c50,515483062,2,1,2019-10-18 10:54:45+00:00,2019-10-18 10:55:20+00:00,0,0,2,0.000000,35.0,False,False,10,Friday,10
1,00000056-a206-40dd-b174-a072550fa38c,513782162,8,7,2019-10-31 06:23:12+00:00,2019-10-31 06:31:25+00:00,0,0,8,0.000000,493.0,False,False,6,Thursday,10
2,0000007c-adbf-4ed7-af17-d1fef9763d67,560165420,1,1,2019-11-18 09:16:19+00:00,2019-11-18 09:16:19+00:00,0,0,1,0.000000,0.0,False,False,9,Monday,11
3,00000083-8816-4d58-a9b8-f52f54186edc,546521725,18,14,2019-10-06 11:24:45+00:00,2019-10-06 11:34:30+00:00,1,1,16,289.519989,585.0,True,False,11,Sunday,10
4,0000009d-1f5b-40b9-bd23-db4f3d973ae3,457789173,1,1,2019-11-13 06:02:54+00:00,2019-11-13 06:02:54+00:00,0,0,1,0.000000,0.0,False,False,6,Wednesday,11

In [4]:
merged = sf_df.merge(df, on='user_id', how='left')

In [5]:
merged

,user_session,user_id,n_events,unique_products,session_start,session_end,n_carts,n_purchases,n_views,session_revenue,duration_seconds,converted,cart_abandoned,hour_of_day,day_of_week,month,cluster_id,cluster_label
0,00000042-3e3f-42f9-810d-f3d264139c50,515483062,2,1,2019-10-18 10:54:45+00:00,2019-10-18 10:55:20+00:00,0,0,2,0.000000,35.0,False,False,10,Friday,10,2,Active Browsers
1,00000056-a206-40dd-b174-a072550fa38c,513782162,8,7,2019-10-31 06:23:12+00:00,2019-10-31 06:31:25+00:00,0,0,8,0.000000,493.0,False,False,6,Thursday,10,3,Engaged Buyers
2,0000007c-adbf-4ed7-af17-d1fef9763d67,560165420,1,1,2019-11-18 09:16:19+00:00,2019-11-18 09:16:19+00:00,0,0,1,0.000000,0.0,False,False,9,Monday,11,2,Active Browsers
3,00000083-8816-4d58-a9b8-f52f54186edc,546521725,18,14,2019-10-06 11:24:45+00:00,2019-10-06 11:34:30+00:00,1,1,16,289.519989,585.0,True,False,11,Sunday,10,3,Engaged Buyers
4,0000009d-1f5b-40b9-bd23-db4f3d973ae3,457789173,1,1,2019-11-13 06:02:54+00:00,2019-11-13 06:02:54+00:00,0,0,1,0.000000,0.0,False,False,6,Wednesday,11,2,Active Browsers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23016645,fffffbbc-3c59-46fb-9165-fa46f027e332,558066678,1,1,2019-11-11 08:33:43+00:00,2019-11-11 08:33:43+00:00,0,0,1,0.000000,0.0,False,False,8,Monday,11,2,Active Browsers
23016646,fffffbbe-9f76-403b-b17c-e7c68c48ea1c,548169601,4,4,2019-11-17 09:43:04+00:00,2019-11-17 09:48:15+00:00,0,0,4,0.000000,311.0,False,False,9,Sunday,11,3,Engaged Buyers
23016647,fffffc65-7ce9-435c-8b72-1d9f7062fe77,515828621,2,2,2019-10-11 06:10:23+00:00,2019-10-11 06:10:54+00:00,0,0,2,0.000000,31.0,False,False,6,Friday,10,2,Active Browsers
23016648,fffffd01-5f95-4916-b2dd-491c603d6c9c,519073108,6,1,2019-11-17 14:07:11+00:00,2019-11-17 14:12:46+00:00,2,1,3,128.419998,335.0,True,False,14,Sunday,11,3,Engaged Buyers
23016649,fffffde2-4522-4b44-8a32-510c55739ba1,522079814,1,1,2019-11-30 10:29:57+00:00,2019-11-30 10:29:57+00:00,0,0,1,0.000000,0.0,False,False,10,Saturday,11,0,Passive Browsers

In [6]:
new_merged = (
    merged
    .groupby(['user_id', 'cluster_label'])
    .agg({
        'n_events': 'sum',
        'unique_products': 'sum',
        'n_views': 'sum',
        'n_carts': 'sum',
        'n_purchases': 'sum',
        'session_revenue': 'sum',
        'duration_seconds': 'sum',
    })
    .reset_index()
)

new_merged

,user_id,cluster_label,n_events,unique_products,n_views,n_carts,n_purchases,session_revenue,duration_seconds
0,10300217,Passive Browsers,1,1,1,0,0,0.0,0.0
1,29515875,Active Browsers,11,8,11,0,0,0.0,111.0
2,31198833,Active Browsers,20,18,20,0,0,0.0,1973.0
3,33869381,Passive Browsers,1,1,1,0,0,0.0,0.0
4,34916060,Passive Browsers,1,1,1,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
5316555,579969605,Passive Browsers,1,1,1,0,0,0.0,0.0
5316556,579969658,Passive Browsers,1,1,1,0,0,0.0,0.0
5316557,579969711,Passive Browsers,3,1,3,0,0,0.0,13.0
5316558,579969767,Passive Browsers,1,1,1,0,0,0.0,0.0
5316559,579969851,Passive Browsers,1,1,1,0,0,0.0,0.0

Analysis can describe differences between groups with statistical rigor, but cannot establish that any one factor caused those differences. All conclusions are associational, not causal. This limitation is explicitly acknowledged in the notebook.

Questions
Do passive browsers view more items?

Do active browsers have a higher cart rate/purchase rate than passive browsers?

Do buyers (one-time and engaged) have a higher purchase rate than the browser clusters?

Do buyers spend as much time on the website?

Do active browsers spend more money than buyers?

Question 1:
# Is there a difference in view counts between the clusters?
Null Hypothesis: All four groups have the same view counts distribution.

Alternative Hypothesis: At least one of the four has a differing view count distribution.

In [7]:
from scipy.stats import ttest_ind

# Split groups
active = new_merged[new_merged['cluster_label'] == 'Active Browsers']['n_views']
passive = new_merged[new_merged['cluster_label'] == 'Passive Browsers']['n_views']
one_time_buyers = new_merged[new_merged['cluster_label'] == 'One Time Buyers']['n_views']
engaged_buyers = new_merged[new_merged['cluster_label'] == 'Engaged Buyers']['n_views']

from scipy.stats import mannwhitneyu

stat1, p_value1 = mannwhitneyu(active, passive, alternative='two-sided')
stat2, p_value2 = mannwhitneyu(active, one_time_buyers, alternative='two-sided')
stat3, p_value3 = mannwhitneyu(active, engaged_buyers, alternative='two-sided')
stat4, p_value4 = mannwhitneyu(one_time_buyers, passive, alternative='two-sided')
stat5, p_value5 = mannwhitneyu(engaged_buyers, passive, alternative='two-sided')
stat6, p_value6 = mannwhitneyu(one_time_buyers, engaged_buyers, alternative='two-sided')

print("Active-Passive T-Statistic:", stat1)
print("Active-Passive P-value:", p_value1)
print("Active-OneTimeBuyer T-Statistic:", stat2)
print("Active-OneTimeBuyer P-value:", p_value2)
print("Active-EngagedBuyer T-Statistic:", stat3)
print("Active-EngagedBuyer P-value:", p_value3)
print("OneTimeBuyer-Passive T-Statistic:", stat4)
print("OneTimeBuyer-Passive P-value:", p_value4)
print("EngagedBuyer-Passive T-Statistic:", stat5)
print("EngagedBuyer-Passive P-value:", p_value5)
print("OneTimeBuyer-EngagedBuyer T-Statistic:", stat6)
print("OneTimeBuyer-EngagedBuyer P-value:", p_value6)

Active-Passive T-Statistic: 4304705589473.5
Active-Passive P-value: 0.0
Active-OneTimeBuyer T-Statistic: 216513164850.0
Active-OneTimeBuyer P-value: 0.0
Active-EngagedBuyer T-Statistic: 225415225435.0
Active-EngagedBuyer P-value: 0.0
OneTimeBuyer-Passive T-Statistic: 382600962656.5
OneTimeBuyer-Passive P-value: 0.0
EngagedBuyer-Passive T-Statistic: 1605166554355.5
EngagedBuyer-Passive P-value: 0.0
OneTimeBuyer-EngagedBuyer T-Statistic: 2148255583.0
OneTimeBuyer-EngagedBuyer P-value: 0.0

In [8]:
print("Active Browser's median views:", active.median())
print("Passive Browser's median views:", passive.median())
print("One Time Buyer's median views:", one_time_buyers.median())
print("Engaged Buyer's median views:", engaged_buyers.median())

Active Browser's median views: 23.0
Passive Browser's median views: 2.0
One Time Buyer's median views: 4.0
Engaged Buyer's median views: 42.0

Conducted a non-parametric Mann-Whitney U test because the distribution was not assumed to be normal. The p-values for each difference was less than 0.05 so each cluster's view count distribution is significantly different.

# Is there a difference in cart rate between clusters?
Null Hypothesis: All four groups have the same cart rates.

Alternative Hypothesis: At least one of the four has a differing cart rate.

In [9]:
from statsmodels.stats.proportion import proportions_ztest

grouped = new_merged.groupby('cluster_label').agg({
    'n_carts': 'sum',
    'n_views': 'sum'
})

active_cart = grouped.loc['Active Browsers', 'n_carts']
active_total   = grouped.loc['Active Browsers', 'n_views']

passive_cart = grouped.loc['Passive Browsers', 'n_carts']
passive_total   = grouped.loc['Passive Browsers', 'n_views']

one_time_buyer_cart = grouped.loc['One Time Buyers', 'n_carts']
one_time_buyer_total   = grouped.loc['One Time Buyers', 'n_views']

engaged_buyer_cart = grouped.loc['Engaged Buyers', 'n_carts']
engaged_buyer_total   = grouped.loc['Engaged Buyers', 'n_views']

stat1, p_value1 = proportions_ztest(
    [active_cart, passive_cart],
    [active_total, passive_total]
)

stat2, p_value2 = proportions_ztest(
    [active_cart, one_time_buyer_cart],
    [active_total, one_time_buyer_total]
)

stat3, p_value3 = proportions_ztest(
    [active_cart, engaged_buyer_cart],
    [active_total, engaged_buyer_total]
)

stat4, p_value4 = proportions_ztest(
    [one_time_buyer_cart, passive_cart],
    [one_time_buyer_total, passive_total]
)

stat5, p_value5 = proportions_ztest(
    [engaged_buyer_cart, passive_cart],
    [engaged_buyer_total, passive_total]
)

stat6, p_value6 = proportions_ztest(
    [one_time_buyer_cart, engaged_buyer_cart],
    [one_time_buyer_total, engaged_buyer_total]
)

print(f"Active-Passive Z-stat: {stat1:.3f}")
print(f"Active-Passive P-value: {p_value1:.4f}")

print(f"Active-OneTimeBuyer Z-stat: {stat2:.3f}")
print(f"Active-OneTimeBuyer P-value: {p_value2:.4f}")

print(f"Active-EngagedBuyer Z-stat: {stat3:.3f}")
print(f"Active-EngagedBuyer P-value: {p_value3:.4f}")

print(f"OneTimeBuyer-Passive Z-stat: {stat4:.3f}")
print(f"OneTimeBuyer-Passive P-value: {p_value4:.4f}")

print(f"EngagedBuyer-Passive Z-stat: {stat5:.3f}")
print(f"EngagedBuyer-Passive P-value: {p_value5:.4f}")

print(f"OneTimeBuyer-EngagedBuyer Z-stat: {stat6:.3f}")
print(f"OneTimeBuyer-EngagedBuyer P-value: {p_value6:.4f}")

Active-Passive Z-stat: 143.926
Active-Passive P-value: 0.0000
Active-OneTimeBuyer Z-stat: -1846.287
Active-OneTimeBuyer P-value: 0.0000
Active-EngagedBuyer Z-stat: -1103.297
Active-EngagedBuyer P-value: 0.0000
OneTimeBuyer-Passive Z-stat: 1551.279
OneTimeBuyer-Passive P-value: 0.0000
EngagedBuyer-Passive Z-stat: 711.832
EngagedBuyer-Passive P-value: 0.0000
OneTimeBuyer-EngagedBuyer Z-stat: 934.392
OneTimeBuyer-EngagedBuyer P-value: 0.0000

In [10]:
print(f"Active Proportion: {active_cart}/{active_total} = {active_cart/active_total}")
print(f"Passive Proportion: {passive_cart}/{passive_total} = {passive_cart/passive_total}")
print(f"One Time Buyers Proportion: {one_time_buyer_cart}/{one_time_buyer_total} = {one_time_buyer_cart/one_time_buyer_total}")
print(f"Engaged Buyers Proportion: {engaged_buyer_cart}/{engaged_buyer_total} = {engaged_buyer_cart/engaged_buyer_total}")

Active Proportion: 985294/52861316 = 0.018639225705239727
Passive Proportion: 163275/12795413 = 0.012760432195506311
One Time Buyers Proportion: 300488/983648 = 0.3054832623052149
Engaged Buyers Proportion: 2379392/37691463 = 0.06312814124514084

Conducted a proportion z-test because we want to compare probability outcome rather than distributions. The p-values for each difference was less than 0.05 so each cluster's probability of carting an item is significantly different.

# Is there a difference in purchase rate between the clusters?

Null Hypothesis: All four groups have the same purchase rates.

Alternative Hypothesis: At least one of the four has a differing purchase rate.

In [11]:
from statsmodels.stats.proportion import proportions_ztest

grouped = new_merged.groupby('cluster_label').agg({
    'n_purchases': 'sum',
    'n_views': 'sum'
})

active_purchase = grouped.loc['Active Browsers', 'n_purchases']
active_total   = grouped.loc['Active Browsers', 'n_views']

passive_purchase = grouped.loc['Passive Browsers', 'n_purchases']
passive_total   = grouped.loc['Passive Browsers', 'n_views']

one_time_buyer_purchase = grouped.loc['One Time Buyers', 'n_purchases']
one_time_buyer_total   = grouped.loc['One Time Buyers', 'n_views']

engaged_buyer_purchase = grouped.loc['Engaged Buyers', 'n_purchases']
engaged_buyer_total   = grouped.loc['Engaged Buyers', 'n_views']

stat1, p_value1 = proportions_ztest(
    [active_purchase, passive_purchase],
    [active_total, passive_total]
)

stat2, p_value2 = proportions_ztest(
    [active_purchase, one_time_buyer_purchase],
    [active_total, one_time_buyer_total]
)

stat3, p_value3 = proportions_ztest(
    [active_purchase, engaged_buyer_purchase],
    [active_total, engaged_buyer_total]
)

stat4, p_value4 = proportions_ztest(
    [one_time_buyer_purchase, passive_purchase],
    [one_time_buyer_total, passive_total]
)

stat5, p_value5 = proportions_ztest(
    [engaged_buyer_purchase, passive_purchase],
    [engaged_buyer_total, passive_total]
)

stat6, p_value6 = proportions_ztest(
    [one_time_buyer_purchase, engaged_buyer_purchase],
    [one_time_buyer_total, engaged_buyer_total]
)

print(f"Active-Passive Z-stat: {stat1:.3f}")
print(f"Active-Passive P-value: {p_value1:.4f}")

print(f"Active-OneTimeBuyer Z-stat: {stat2:.3f}")
print(f"Active-OneTimeBuyer P-value: {p_value2:.4f}")

print(f"Active-EngagedBuyer Z-stat: {stat3:.3f}")
print(f"Active-EngagedBuyer P-value: {p_value3:.4f}")

print(f"OneTimeBuyer-Passive Z-stat: {stat4:.3f}")
print(f"OneTimeBuyer-Passive P-value: {p_value4:.4f}")

print(f"EngagedBuyer-Passive Z-stat: {stat5:.3f}")
print(f"EngagedBuyer-Passive P-value: {p_value5:.4f}")

print(f"OneTimeBuyer-EngagedBuyer Z-stat: {stat6:.3f}")
print(f"OneTimeBuyer-EngagedBuyer P-value: {p_value6:.4f}")

Active-Passive Z-stat: -34.337
Active-Passive P-value: 0.0000
Active-OneTimeBuyer Z-stat: -3969.563
Active-OneTimeBuyer P-value: 0.0000
Active-EngagedBuyer Z-stat: -1337.379
Active-EngagedBuyer P-value: 0.0000
OneTimeBuyer-Passive Z-stat: 2013.670
OneTimeBuyer-Passive P-value: 0.0000
EngagedBuyer-Passive Z-stat: 660.951
EngagedBuyer-Passive P-value: 0.0000
OneTimeBuyer-EngagedBuyer Z-stat: 1388.379
OneTimeBuyer-EngagedBuyer P-value: 0.0000

In [12]:
print(f"Active Proportion: {active_purchase}/{active_total} = {active_purchase/active_total}")
print(f"Passive Proportion: {passive_purchase}/{passive_total} = {passive_purchase/passive_total}")
print(f"One Time Buyers Proportion: {one_time_buyer_purchase}/{one_time_buyer_total} = {one_time_buyer_purchase/one_time_buyer_total}")
print(f"Engaged Buyers Proportion: {engaged_buyer_purchase}/{engaged_buyer_total} = {engaged_buyer_purchase/engaged_buyer_total}")

Active Proportion: 23754/52861316 = 0.0004493645220637337
Passive Proportion: 8797/12795413 = 0.0006875120013711164
One Time Buyers Proportion: 314281/983648 = 0.31950555483262305
Engaged Buyers Proportion: 1312871/37691463 = 0.03483205202196582

Conducted a proportion z-test because we want to compare probability outcome rather than distributions. The p-values for each difference was less than 0.05 so each cluster's probability of carting an item is significantly different.

# Is there a difference in time spent browsing between the clusters?

Null Hypothesis: All four groups have the same browsing time distribution.

Alternative Hypothesis: At least one of the four has a differing browsing time distribution.

In [13]:
active = new_merged[new_merged['cluster_label'] == 'Active Browsers']['duration_seconds']
passive = new_merged[new_merged['cluster_label'] == 'Passive Browsers']['duration_seconds']
one_time_buyers = new_merged[new_merged['cluster_label'] == 'One Time Buyers']['duration_seconds']
engaged_buyers = new_merged[new_merged['cluster_label'] == 'Engaged Buyers']['duration_seconds']

from scipy.stats import mannwhitneyu

stat1, p_value1 = mannwhitneyu(active, passive, alternative='two-sided')
stat2, p_value2 = mannwhitneyu(active, one_time_buyers, alternative='two-sided')
stat3, p_value3 = mannwhitneyu(active, engaged_buyers, alternative='two-sided')
stat4, p_value4 = mannwhitneyu(one_time_buyers, passive, alternative='two-sided')
stat5, p_value5 = mannwhitneyu(engaged_buyers, passive, alternative='two-sided')
stat6, p_value6 = mannwhitneyu(one_time_buyers, engaged_buyers, alternative='two-sided')

print(f"Active-Passive Stat: {stat1:.3f}")
print(f"Active-Passive P-value: {p_value1:.3f}")
print(f"Active-OneTimeBuyer Stat: {stat2:.3f}")
print(f"Active-OneTimeBuyer P-value: {p_value2:.3f}")
print(f"Active-EngagedBuyer Stat: {stat3:.3f}")
print(f"Active-EngagedBuyer P-value: {p_value3:.3f}")
print(f"OneTimeBuyer-Passive Stat: {stat4:.3f}")
print(f"OneTimeBuyer-Passive P-value: {p_value4:.3f}")
print(f"EngagedBuyer-Passive Stat: {stat5:.3f}")
print(f"EngagedBuyer-Passive P-value: {p_value5:.3f}")
print(f"OneTimeBuyer-EngagedBuyer Stat: {stat6:.3f}")
print(f"OneTimeBuyer-EngagedBuyer P-value: {p_value6:.3f}")

Active-Passive Stat: 4059911480732.500
Active-Passive P-value: 0.000
Active-OneTimeBuyer Stat: 180107878704.000
Active-OneTimeBuyer P-value: 0.000
Active-EngagedBuyer Stat: 218171404145.500
Active-EngagedBuyer P-value: 0.000
OneTimeBuyer-Passive Stat: 463705006448.000
OneTimeBuyer-Passive P-value: 0.000
EngagedBuyer-Passive Stat: 1573145829659.000
EngagedBuyer-Passive P-value: 0.000
OneTimeBuyer-EngagedBuyer Stat: 6414632261.500
OneTimeBuyer-EngagedBuyer P-value: 0.000

In [14]:
print(f"Active Browsers Median Time Spent (seconds): {active.median():.3f}")
print(f"Passive Browsers Median Time Spent (seconds): {passive.median():.3f}")
print(f"One Time Buyers Median Time Spent (seconds): {one_time_buyers.median():.3f}")
print(f"Engaged Buyers Median Time Spent (seconds): {engaged_buyers.median():.3f}")

Active Browsers Median Time Spent (seconds): 1289.000
Passive Browsers Median Time Spent (seconds): 23.000
One Time Buyers Median Time Spent (seconds): 358.000
Engaged Buyers Median Time Spent (seconds): 2819.000

Conducted a non-parametric Mann-Whitney U test because the distribution was not assumed to be normal. The p-values for each difference was less than 0.05 so each cluster's view count distribution is significantly different.

# Is there a difference between total money spent between the clusters?

In [15]:
active = new_merged[new_merged['cluster_label'] == 'Active Browsers']['session_revenue']
passive = new_merged[new_merged['cluster_label'] == 'Passive Browsers']['session_revenue']
one_time_buyers = new_merged[new_merged['cluster_label'] == 'One Time Buyers']['session_revenue']
engaged_buyers = new_merged[new_merged['cluster_label'] == 'Engaged Buyers']['session_revenue']

from scipy.stats import mannwhitneyu

stat1, p_value1 = mannwhitneyu(active, passive, alternative='two-sided')
stat2, p_value2 = mannwhitneyu(active, one_time_buyers, alternative='two-sided')
stat3, p_value3 = mannwhitneyu(active, engaged_buyers, alternative='two-sided')
stat4, p_value4 = mannwhitneyu(one_time_buyers, passive, alternative='two-sided')
stat5, p_value5 = mannwhitneyu(engaged_buyers, passive, alternative='two-sided')
stat6, p_value6 = mannwhitneyu(one_time_buyers, engaged_buyers, alternative='two-sided')

print(f"Active-Passive Stat: {stat1:.3f}")
print(f"Active-Passive P-value: {p_value1:.3f}")
print(f"Active-OneTimeBuyer Stat: {stat2:.3f}")
print(f"Active-OneTimeBuyer P-value: {p_value2:.3f}")
print(f"Active-EngagedBuyer Stat: {stat3:.3f}")
print(f"Active-EngagedBuyer P-value: {p_value3:.3f}")
print(f"OneTimeBuyer-Passive Stat: {stat4:.3f}")
print(f"OneTimeBuyer-Passive P-value: {p_value4:.3f}")
print(f"EngagedBuyer-Passive Stat: {stat5:.3f}")
print(f"EngagedBuyer-Passive P-value: {p_value5:.3f}")
print(f"OneTimeBuyer-EngagedBuyer Stat: {stat6:.3f}")
print(f"OneTimeBuyer-EngagedBuyer P-value: {p_value6:.3f}")

Active-Passive Stat: 2269444951971.000
Active-Passive P-value: 0.000
Active-OneTimeBuyer Stat: 215513149.500
Active-OneTimeBuyer P-value: 0.000
Active-EngagedBuyer Stat: 807556606.500
Active-EngagedBuyer P-value: 0.000
OneTimeBuyer-Passive Stat: 560483201482.000
OneTimeBuyer-Passive P-value: 0.000
EngagedBuyer-Passive Stat: 1629970151497.000
EngagedBuyer-Passive P-value: 0.000
OneTimeBuyer-EngagedBuyer Stat: 43267804057.500
OneTimeBuyer-EngagedBuyer P-value: 0.000

In [16]:
print(f"Active Browsers Mean Money Spent: {active.mean():.3f}")
print(f"Passive Browsers Mean Money Spent: {passive.mean():.3f}")
print(f"One Time Buyers Mean Money Spent: {one_time_buyers.mean():.3f}")
print(f"Engaged Buyers Mean Money Spent: {engaged_buyers.mean():.3f}")

Active Browsers Mean Money Spent: 0.707
Passive Browsers Mean Money Spent: 0.160
One Time Buyers Mean Money Spent: 633.495
Engaged Buyers Mean Money Spent: 798.793

Conducted a non-parametric Mann-Whitney U test because the distribution was not assumed to be normal. The p-values for each difference was less than 0.05 so each cluster's view count distribution is significantly different.